### ISSUE TITLE
Text not respecting screen/print boundries

### ISSUE THREAD

**Issue by MindMapMaker** [BerndGabriel/HtmlViewer#88] opened 2015-05-26 23:22 UTC
If a webpage has a graphic or line or table that extends to the right beyond the viewport/window boundary then all the following text also uses that new extended boundary. IE doesn't do this. In IE even if a graphic or line or table extends beyond the right margin the text above and below is wrapped to the window dimensions. 
This is critical for viewing and printing emails. It is a little thing if a graphic is mis-sized beyond the margin and prints on two pages. Same with tables, not a big deal if it prints on a second page. However with HTMLViewer all following text then will wrap across two pages also. IE is more pragmatic and wraps the text to window dimensions and wraps to paper dimensions. I hacked htmlviewer and just ignored the width specification on h elements and now it automatically adjusts to window width. I am researching if I can do the same thing with graphics with a width gt 500px.

**Comment by BerndGabriel** [comment] 2015-06-10 19:32
Could you please post or mail a little example that clearly exposes the bad behaviour. Thanks in advance.

**Comment by silvestru** [comment] 2016-03-31 16:30
The HTML file from the attached archive clearly exposes that bad behaviour. It is very visible when you do a print preview and then navigate through pages - you will see every second page is empty.

Please not that the original 9.45 version, IE, Firefox and Chrome shows that file correctly.

[ie and 9-45](https://cloud.githubusercontent.com/assets/1853968/14183031/c1eb500c-f776-11e5-8c40-9733865c5178.jpg)


[TestBoundaries.zip](https://github.com/BerndGabriel/HtmlViewer/files/198040/TestBoundaries.zip)

**Comment by JohnSylver** [comment] 2016-06-01 15:09
Is there a hope this issue will be fixed? Thanks in advance.

**Comment by BerndGabriel** [comment] 2016-06-01 19:01
Sorry, John. It's not a bug, it's a feature! HtmlViewer can print as many pages horizontally as are needed. A very useful feature for e.g. huge time tables. For those who don't like it there is property PrintMaxHPages. By default it is set to 2. If you set it to 1 it prints like other browsers.

**Closed by BerndGabriel** 2016-06-01 19:01 UTC
Labels: bug?, won't fix
