### ISSUE TITLE
(Question) Is there a way to use border-radius?

### ISSUE THREAD

**Issue by chriseana** [BerndGabriel/HtmlViewer#262] opened 2019-03-29 17:35 UTC
Hi Folks,
Is there a way to use border-radius:25px, for example, inside my HTML?
Beat regards

**Comment by BerndGabriel** [comment] 2019-06-23 12:53
No, currently there are no plans to add 'eye candy' properties.

**Comment by BerndGabriel** [comment] 2019-06-23 12:54
Duplicate of #206

**Closed** 2019-06-23 12:54 UTC
